export const spanishWords = [
  { word: "El horario", meaning: "Schedule", sentence: "¿Cuál es tu horario de trabajo?", sentence_en: "What is your work schedule?" },
  { word: "La reunión", meaning: "Meeting", sentence: "Tengo una reunión importante mañana.", sentence_en: "I have an important meeting tomorrow." },
  { word: "El descanso", meaning: "Break", sentence: "Necesito un descanso de cinco minutos.", sentence_en: "I need a five-minute break." },
  { word: "La tarea", meaning: "Task", sentence: "He completado todas mis tareas.", sentence_en: "I have completed all my tasks." },
  { word: "El equipo", meaning: "Team", sentence: "Nuestro equipo trabaja muy bien juntos.", sentence_en: "Our team works very well together." },
  { word: "El proyecto", meaning: "Project", sentence: "El proyecto debe terminarse el viernes.", sentence_en: "The project must be finished on Friday." },
  { word: "La fecha límite", meaning: "Deadline", sentence: "La fecha límite es estricta.", sentence_en: "The deadline is strict." },
  { word: "El éxito", meaning: "Success", sentence: "El evento fue un gran éxito.", sentence_en: "The event was a great success." },
  { word: "La oportunidad", meaning: "Opportunity", sentence: "Esta es una gran oportunidad para aprender.", sentence_en: "This is a great opportunity to learn." },
  { word: "El desafío", meaning: "Challenge", sentence: "Me gustan los desafíos nuevos.", sentence_en: "I like new challenges." },
  { word: "La solución", meaning: "Solution", sentence: "Debemos encontrar una solución rápida.", sentence_en: "We must find a quick solution." },
  { word: "El objetivo", meaning: "Goal", sentence: "Mi objetivo es mejorar mi español.", sentence_en: "My goal is to improve my Spanish." },
  { word: "La experiencia", meaning: "Experience", sentence: "Tengo mucha experiencia en este campo.", sentence_en: "I have a lot of experience in this field." },
  { word: "El conocimiento", meaning: "Knowledge", sentence: "El conocimiento es poder.", sentence_en: "Knowledge is power." },
  { word: "La habilidad", meaning: "Skill", sentence: "Es una habilidad muy útil.", sentence_en: "It is a very useful skill." },
  { word: "El esfuerzo", meaning: "Effort", sentence: "Vale la pena el esfuerzo.", sentence_en: "It is worth the effort." },
  { word: "La paciencia", meaning: "Patience", sentence: "La paciencia es una virtud.", sentence_en: "Patience is a virtue." },
  { word: "La confianza", meaning: "Trust/Confidence", sentence: "Tengo confianza en ti.", sentence_en: "I have confidence in you." },
  { word: "El respeto", meaning: "Respect", sentence: "El respeto mutuo es importante.", sentence_en: "Mutual respect is important." },
  { word: "La responsabilidad", meaning: "Responsibility", sentence: "Es mi responsabilidad.", sentence_en: "It is my responsibility." },
  { word: "El compromiso", meaning: "Commitment", sentence: "Tengo un compromiso con mi trabajo.", sentence_en: "I have a commitment to my work." },
  { word: "La colaboración", meaning: "Collaboration", sentence: "La colaboración es clave.", sentence_en: "Collaboration is key." },
  { word: "La innovación", meaning: "Innovation", sentence: "Buscamos la innovación constante.", sentence_en: "We seek constant innovation." },
  { word: "El desarrollo", meaning: "Development", sentence: "El desarrollo personal es importante.", sentence_en: "Personal development is important." },
  { word: "La mejora", meaning: "Improvement", sentence: "Siempre hay espacio para la mejora.", sentence_en: "There is always room for improvement." },
  { word: "El resultado", meaning: "Result", sentence: "Esperamos buenos resultados.", sentence_en: "We expect good results." },
  { word: "La decisión", meaning: "Decision", sentence: "Fue una decisión difícil.", sentence_en: "It was a difficult decision." },
  { word: "El plan", meaning: "Plan", sentence: "Todo salió según el plan.", sentence_en: "Everything went according to plan." },
  { word: "La meta", meaning: "Goal/Target", sentence: "Alcanzamos nuestra meta mensual.", sentence_en: "We reached our monthly goal." },
  { word: "El futuro", meaning: "Future", sentence: "El futuro parece brillante.", sentence_en: "The future looks bright." }
];
